#.travis.yml
addons:
  chrome: stable

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master
    - coveralls-integration-and-badge

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - ng -v


script:
  - ng build --prod
  - ng test --code-coverage --watch false

after_success:
  - coveralls

notifications:
  email:
    on_failure: change
    on_success: change
